# Generated by Django 4.1.1 on 2022-09-13 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TwitterUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name="Tweets",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("text", models.CharField(max_length=280)),
                ("lang", models.CharField(max_length=2)),
                ("created_at", models.DateTimeField()),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                ("last_modification", models.DateTimeField(auto_now=True)),
                ("public_metrics", models.CharField(max_length=500)),
                ("referenced_tweets", models.CharField(max_length=500)),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="twt_db.twitteruser",
                    ),
                ),
            ],
        ),
    ]
