# Generated by Django 4.1.1 on 2022-09-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twt_db", "0002_tweets_conversation_id_tweets_in_reply_to_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweets",
            name="query",
            field=models.CharField(default=None, max_length=280),
            preserve_default=False,
        ),
    ]
